services:
  vectorestore:
    image: opensearchproject/opensearch:1.3.19
    container_name: vectorestore
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9600:9600"
  
  rag-app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - vectorestore
    